
export const LIST_ENVELOPES_START = 'LIST_ENVELOPES_START';
export const LIST_ENVELOPES_DATA_RECVD = 'LIST_ENVELOPES_DATA_RECVD';
export const LIST_ENVELOPES_ERROR = 'LIST_ENVELOPES_ERROR';
export const LIST_ENVELOPES_RESET_ENV_LIST = 'LIST_ENVELOPES_RESET_ENV_LIST';

export const DS_AUTH_FAIL = 'DS_AUTH_FAIL';
export const DS_AUTH_LOGOUT = 'DS_AUTH_LOGOUT';
export const DS_AUTH_START = 'DS_AUTH_START';
export const DS_AUTH_CHECK_STATE = 'DS_AUTH_CHECK_STATE';
export const DS_AUTH_CHECK_CONFIG = 'DS_AUTH_CHECK_CONFIG';
export const DS_AUTH_RECD_TOKEN = 'DS_AUTH_RECD_TOKEN';
export const DS_AUTH_RECD_USER_INFO = 'DS_AUTH_RECD_USER_INFO';
export const DS_AUTH_SET_AUTH_REDIRECT = 'DS_AUTH_SET_AUTH_REDIRECT';
export const DS_AUTH_NEW_AUTHENTICATION = 'DS_AUTH_NEW_AUTHENTICATION';
export const DS_AUTH_NEW_AUTHENTICATION_REDIRECTED = 'DS_AUTH_NEW_AUTHENTICATION_REDIRECTED';
export const DS_AUTH_SET_ROUTER_REPLACE = 'DS_AUTH_SET_ROUTER_REPLACE';
export const DS_AUTH_RESTORE_FROM_STORAGE = 'DS_AUTH_RESTORE_FROM_STORAGE';
export const DS_AUTH_FINISHED_STARTUP = 'DS_AUTH_FINISHED_STARTUP';

export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';

export const ALERT = 'ALERT';
export const ALERT_RESET = 'ALERT_RESET';

export const SEND_SIGN_ENV_START = 'SEND_SIGN_ENV_START';
export const SEND_SIGN_ENV_ID_RECVD = 'SEND_SIGN_ENV_ID_RECVD';
export const SEND_SIGN_ENV_ERROR = 'SEND_SIGN_ENV_ERROR';